apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-15524
  janus-idp.io/tekton: go-15524
  backstage.io/kubernetes-id: go-15524
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: go-15524
resources:
- deployment.yaml
- route.yaml
- service.yaml
